# 수동으로 트리거하여 최신 커밋을 분석하는 워크플로우
name: Claude Commit Analysis

on:
  # 수동 실행 트리거 - GitHub Actions 탭에서 직접 실행할 수 있습니다
  workflow_dispatch:
    inputs:
      analysis_type:
        description: "Type of analysis to perform"
        required: true
        type: choice
        options:
          - summarize-commit
          - security-review
        default: "summarize-commit"

jobs:
  analyze-commit:
    runs-on: ubuntu-latest
    # 필요한 권한 설정
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2 # 최신 커밋을 분석하려면 최소 2개의 커밋이 필요합니다

      # Claude를 사용하여 커밋 분석을 실행합니다
      - name: Run Claude Analysis
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            REPO: ${{ github.repository }}
            BRANCH: ${{ github.ref_name }}

            이 저장소의 최신 커밋을 분석해 주세요.

            ${{ github.event.inputs.analysis_type == 'summarize-commit' && '작업: 최신 커밋에서 변경된 내용을 명확하고 간결하게 요약해 주세요. 커밋 메시지, 변경된 파일, 변경 목적을 포함해 주세요.' || '' }}

            ${{ github.event.inputs.analysis_type == 'security-review' && '작업: 최신 커밋에서 잠재적인 보안 취약점을 검토해 주세요. 노출된 비밀 정보, 안전하지 않은 코딩 패턴, 의존성 취약점 또는 기타 보안 문제가 있는지 확인해 주세요. 문제가 발견되면 구체적인 권장 사항을 제시해 주세요.' || '' }}
