name: PR Review with Progress Tracking

# 이 예제는 track_progress 기능을 사용하여 PR 리뷰에 대한
# 시각적 진행 상황 추적을 수행하는 방법을 보여줍니다.
# v0.x 에이전트 모드와 유사한 방식으로 동작합니다.

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  review-with-tracking:
    runs-on: ubuntu-latest
    # 필요한 권한 설정: 코드 읽기, PR 쓰기, OIDC 토큰 발급
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: PR Review with Progress Tracking
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # 진행 상황 추적 활성화
          track_progress: true

          # 리뷰 지침 프롬프트
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            다음 중점 영역에 대해 종합적인 코드 리뷰를 수행하세요:

            1. **코드 품질**
               - 클린 코드 원칙 및 모범 사례 준수 여부
               - 적절한 오류 처리 및 엣지 케이스 대응
               - 코드 가독성 및 유지보수성

            2. **보안**
               - 잠재적인 보안 취약점 점검
               - 입력값 검증(sanitization) 확인
               - 인증/인가 로직 검토

            3. **성능**
               - 잠재적인 성능 병목 지점 식별
               - 데이터베이스 쿼리 효율성 검토
               - 메모리 누수 또는 리소스 문제 확인

            4. **테스트**
               - 충분한 테스트 커버리지 확인
               - 테스트 품질 및 엣지 케이스 검토
               - 누락된 테스트 시나리오 확인

            5. **문서화**
               - 코드에 적절한 문서가 작성되었는지 확인
               - 새로운 기능에 대한 README 업데이트 확인
               - API 문서의 정확성 점검

            특정 이슈에 대해서는 인라인 코멘트를 사용하여 상세한 피드백을 제공하세요.
            전반적인 소감이나 칭찬은 최상위 코멘트를 사용하세요.

          # 종합적인 PR 리뷰를 위한 도구 설정
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*)"

# track_progress가 활성화되면:
# - 진행 상황 체크박스가 포함된 추적 코멘트를 생성합니다
# - 모든 PR 컨텍스트(코멘트, 첨부 파일, 이미지)를 포함합니다
# - 리뷰가 진행됨에 따라 진행 상황을 업데이트합니다
# - 완료 시 완료 표시를 합니다
